# Write your code here :-)
print("+======================+")
print("      HELLO WORLD      ")
print("       by Amber"      )
print("+======================+")
print("")
print("Hello World!")
name = input("What is your name? ")

color = input(f"Hello, {name}! What is your favorite color? ")
print("No way! My favorite color is also " +color)
movie = input("What's your favorite movie? ")
print("What?! My favorite movie is also " +movie)
game = input("What about your favorite game? ")
print(f"Get out of here! My favorite game is {game}, too!")
print("We like the same things! We should be best friends!")